// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(HomeFinanceContext))]
    [Migration("20220214114443_RemovedNavPropertyOperation")]
    partial class RemovedNavPropertyOperation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10m,
                            CategoryId = 1,
                            Date = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2m,
                            CategoryId = 3,
                            Date = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 3,
                            Amount = 220m,
                            CategoryId = 4,
                            Date = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 4,
                            Amount = 40m,
                            CategoryId = 1,
                            Date = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 5,
                            Amount = 140m,
                            CategoryId = 5,
                            Date = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 6,
                            Amount = 5m,
                            CategoryId = 3,
                            Date = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 7,
                            Amount = 2m,
                            CategoryId = 3,
                            Date = new DateTime(2022, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 8,
                            Amount = 53m,
                            CategoryId = 5,
                            Date = new DateTime(2022, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 9,
                            Amount = 10m,
                            CategoryId = 1,
                            Date = new DateTime(2022, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 10,
                            Amount = 300m,
                            CategoryId = 2,
                            Date = new DateTime(2022, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = false
                        },
                        new
                        {
                            Id = 11,
                            Amount = 1000m,
                            CategoryId = 6,
                            Date = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = true
                        },
                        new
                        {
                            Id = 12,
                            Amount = 100m,
                            CategoryId = 7,
                            Date = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsIncome = true
                        });
                });

            modelBuilder.Entity("Common.Models.OperationCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Foodstuffs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rent"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FastFood"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hobby"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Other"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Present"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
